// GENERATED by tools/build_activity.py from TickTick (habits, completed + open tasks).
// Refresh by asking Claude to re-pull TickTick and re-run the script.
const ACTIVITY = {
"asOf": "2026-09-30",
"windowDays": 30,
"routines": {
"body-vitamins-supplements": {
"kind": "habit",
"last": "2026-09-08",
"done": 2,
"expected": 30,
"days": [
"2026-09-05",
"2026-09-08"
],
"skipped": [
"2026-09-01",
"2026-09-02",
"2026-09-16",
"2026-09-25"
]
},
"mind-healthy-minds-session": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 22,
"days": [],
"skipped": [
"2026-09-01",
"2026-09-02",
"2026-09-09",
"2026-09-16",
"2026-09-25"
]
},
"body-washing-face-complexion": {
"kind": "habit",
"last": "2026-09-08",
"done": 2,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-08"
]
},
"body-moisturize-body": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 17,
"days": [],
"skipped": [
"2026-09-02",
"2026-09-09"
]
},
"cleaning-wipe-room-surfaces": {
"kind": "habit",
"last": "2026-09-27",
"done": 2,
"expected": 17,
"days": [
"2026-09-01",
"2026-09-27"
]
},
"cleaning-vacuum-room": {
"kind": "habit",
"last": "2026-09-27",
"done": 3,
"expected": 17,
"days": [
"2026-09-01",
"2026-09-12",
"2026-09-27"
]
},
"dog-walks": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 12,
"days": []
},
"body-weekly-bath": {
"kind": "habit",
"last": "2026-09-24",
"done": 7,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-07",
"2026-09-08",
"2026-09-09",
"2026-09-16",
"2026-09-24"
]
},
"dog-weekly-vacuum-marvel": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 13,
"days": [],
"skipped": [
"2026-09-01"
]
},
"dog-play-sessions": {
"kind": "habit",
"last": "2026-09-23",
"done": 1,
"expected": 13,
"days": [
"2026-09-23"
],
"skipped": [
"2026-09-02",
"2026-09-09",
"2026-09-16"
]
},
"body-put-out-gym-clothes": {
"kind": "habit",
"last": "2026-09-01",
"done": 1,
"expected": 26,
"days": [
"2026-09-01"
]
},
"mind-reading": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 10,
"days": [],
"skipped": [
"2026-09-09"
]
},
"mind-smile-to-yourself": {
"kind": "habit",
"last": "2026-09-27",
"done": 12,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-04",
"2026-09-07",
"2026-09-08",
"2026-09-09",
"2026-09-12",
"2026-09-16",
"2026-09-23",
"2026-09-24",
"2026-09-25",
"2026-09-27"
]
},
"mind-journaling": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 30,
"days": [],
"skipped": [
"2026-09-09"
]
},
"soul-vocal-training": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 13,
"days": [],
"skipped": [
"2026-09-02",
"2026-09-09",
"2026-09-16"
]
},
"body-teeth-night": {
"kind": "habit",
"last": "2026-08-31",
"done": 0,
"expected": 30,
"days": []
},
"body-full-gym-session": {
"kind": "habit",
"last": "2026-09-25",
"done": 8,
"expected": 26,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-07",
"2026-09-08",
"2026-09-16",
"2026-09-23",
"2026-09-24",
"2026-09-25"
]
},
"body-active-pt": {
"kind": "habit",
"last": "2026-09-25",
"done": 4,
"expected": 26,
"days": [
"2026-09-07",
"2026-09-16",
"2026-09-23",
"2026-09-25"
],
"skipped": [
"2026-09-01",
"2026-09-02",
"2026-09-08"
]
},
"body-water-intake": {
"kind": "habit",
"last": "2026-09-09",
"done": 2,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-09"
],
"skipped": [
"2026-09-02",
"2026-09-16"
]
},
"body-creatine-fiber": {
"kind": "habit",
"last": null,
"done": 0,
"expected": 30,
"days": [],
"skipped": [
"2026-09-01",
"2026-09-02",
"2026-09-09",
"2026-09-16",
"2026-09-25"
]
},
"cleaning-room-reset": {
"kind": "habit",
"last": "2026-09-27",
"done": 7,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-04",
"2026-09-08",
"2026-09-09",
"2026-09-20",
"2026-09-24",
"2026-09-27"
]
},
"cleaning-kitchen-usable": {
"kind": "habit",
"last": "2026-09-24",
"done": 8,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-07",
"2026-09-09",
"2026-09-12",
"2026-09-16",
"2026-09-23",
"2026-09-24"
]
},
"dog-behavior-training": {
"kind": "habit",
"last": "2026-09-23",
"done": 1,
"expected": 22,
"days": [
"2026-09-23"
],
"skipped": [
"2026-09-01",
"2026-09-02",
"2026-09-09",
"2026-09-16"
]
},
"mind-daytime-rest": {
"kind": "habit",
"last": "2026-09-24",
"done": 5,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-07",
"2026-09-16",
"2026-09-24"
],
"skipped": [
"2026-09-09"
]
},
"body-fruit-vegetable": {
"kind": "habit",
"last": "2026-09-25",
"done": 6,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-08",
"2026-09-09",
"2026-09-16",
"2026-09-25"
]
},
"body-movement-break": {
"kind": "habit",
"last": "2026-09-27",
"done": 8,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-07",
"2026-09-09",
"2026-09-16",
"2026-09-23",
"2026-09-24",
"2026-09-27"
]
},
"soul-creative-tinkering": {
"kind": "habit",
"last": "2026-09-07",
"done": 2,
"expected": 30,
"days": [
"2026-09-01",
"2026-09-07"
],
"skipped": [
"2026-09-09",
"2026-09-16"
]
},
"body-face-shaving": {
"kind": "habit",
"last": "2026-09-07",
"done": 2,
"expected": 10,
"days": [
"2026-09-04",
"2026-09-07"
],
"skipped": [
"2026-09-01"
]
},
"body-body-shaving": {
"kind": "habit",
"last": "2026-09-04",
"done": 1,
"expected": 4,
"days": [
"2026-09-04"
]
},
"body-cardio-training": {
"kind": "habit",
"last": "2026-09-25",
"done": 4,
"expected": 7,
"days": [
"2026-09-01",
"2026-09-04",
"2026-09-08",
"2026-09-25"
]
},
"body-recovery-options": {
"kind": "habit",
"last": "2026-09-24",
"done": 5,
"expected": 23,
"days": [
"2026-09-01",
"2026-09-04",
"2026-09-05",
"2026-09-07",
"2026-09-24"
]
},
"body-abdominal-training": {
"kind": "habit",
"last": "2026-09-07",
"done": 2,
"expected": 7,
"days": [
"2026-09-02",
"2026-09-07"
],
"skipped": [
"2026-09-16"
]
},
"organizing-personal-finance-allocation": {
"kind": "task",
"last": "2026-09-30",
"done": 5,
"expected": 4,
"days": [
"2026-09-02",
"2026-09-09",
"2026-09-16",
"2026-09-25",
"2026-09-30"
],
"nextDue": "2026-10-07"
},
"organizing-digital-declutter": {
"kind": "task",
"last": "2026-09-27",
"done": 4,
"expected": 4,
"days": [
"2026-09-06",
"2026-09-14",
"2026-09-20",
"2026-09-27"
],
"nextDue": "2026-10-04"
},
"cleaning-bathroom-weekly": {
"kind": "task",
"last": "2026-09-26",
"done": 4,
"expected": 4,
"days": [
"2026-09-05",
"2026-09-12",
"2026-09-19",
"2026-09-26"
],
"nextDue": "2026-10-03"
},
"cleaning-vacuum-car": {
"kind": "task",
"last": "2026-09-26",
"done": 4,
"expected": 4,
"days": [
"2026-09-05",
"2026-09-12",
"2026-09-19",
"2026-09-26"
],
"nextDue": "2026-10-03"
},
"dog-marvel-care-note": {
"kind": "task",
"last": "2026-09-25",
"done": 1,
"expected": 21,
"days": [
"2026-09-25"
]
},
"soul-creative-project-menu-note": {
"kind": "task",
"last": "2026-09-25",
"done": 1,
"expected": 30,
"days": [
"2026-09-25"
],
"overdueSince": "2026-09-28"
},
"cleaning-clean-tote-bag": {
"kind": "task",
"last": "2026-09-25",
"done": 4,
"expected": 4,
"days": [
"2026-09-04",
"2026-09-11",
"2026-09-19",
"2026-09-25"
],
"nextDue": "2026-10-02"
},
"cleaning-wash-towels": {
"kind": "task",
"last": "2026-09-25",
"done": 4,
"expected": 4,
"days": [
"2026-09-04",
"2026-09-11",
"2026-09-18",
"2026-09-25"
],
"nextDue": "2026-10-02"
},
"mind-rest-sleep-note": {
"kind": "task",
"last": "2026-09-25",
"done": 2,
"expected": 30,
"days": [
"2026-09-08",
"2026-09-25"
],
"overdueSince": "2026-09-28"
},
"body-gym-standards-note": {
"kind": "task",
"last": "2026-09-08",
"done": 1,
"expected": 26,
"days": [
"2026-09-08"
]
},
"cleaning-clean-laundry": {
"kind": "task",
"last": "2026-09-25",
"done": 4,
"expected": 4,
"days": [
"2026-09-04",
"2026-09-11",
"2026-09-18",
"2026-09-25"
],
"nextDue": "2026-10-02"
},
"mind-open-job-search": {
"kind": "task",
"last": "2026-09-25",
"done": 7,
"expected": 21,
"days": [
"2026-09-09",
"2026-09-10",
"2026-09-14",
"2026-09-18",
"2026-09-23",
"2026-09-24",
"2026-09-25"
],
"overdueSince": "2026-09-28"
},
"body-nutrition-flow-note": {
"kind": "task",
"last": "2026-09-08",
"done": 1,
"expected": 30,
"days": [
"2026-09-08"
],
"overdueSince": "2026-09-28"
},
"mind-weekday-reminders": {
"kind": "task",
"last": "2026-09-25",
"done": 13,
"expected": 21,
"days": [
"2026-09-01",
"2026-09-02",
"2026-09-04",
"2026-09-07",
"2026-09-08",
"2026-09-10",
"2026-09-11",
"2026-09-14",
"2026-09-15",
"2026-09-16",
"2026-09-17",
"2026-09-23",
"2026-09-25"
],
"overdueSince": "2026-09-28"
},
"cleaning-clean-headphones": {
"kind": "task",
"last": "2026-09-25",
"done": 6,
"expected": 9,
"days": [
"2026-09-04",
"2026-09-07",
"2026-09-11",
"2026-09-14",
"2026-09-19",
"2026-09-25"
],
"overdueSince": "2026-09-28"
},
"cleaning-clean-phone-laptop-glasses": {
"kind": "task",
"last": "2026-09-24",
"done": 9,
"expected": 13,
"days": [
"2026-09-01",
"2026-09-03",
"2026-09-05",
"2026-09-08",
"2026-09-12",
"2026-09-15",
"2026-09-17",
"2026-09-19",
"2026-09-24"
],
"overdueSince": "2026-09-29"
},
"organizing-water-plants": {
"kind": "task",
"last": "2026-09-21",
"done": 3,
"expected": 4,
"days": [
"2026-09-07",
"2026-09-14",
"2026-09-21"
],
"overdueSince": "2026-09-28"
},
"soul-main-session": {
"kind": "task",
"last": "2026-09-22",
"done": 4,
"expected": 4,
"days": [
"2026-09-01",
"2026-09-08",
"2026-09-15",
"2026-09-22"
],
"overdueSince": "2026-09-29"
},
"body-nail-cuticle-care": {
"kind": "task",
"last": "2026-09-23",
"done": 4,
"expected": 4,
"days": [
"2026-09-02",
"2026-09-09",
"2026-09-16",
"2026-09-23"
],
"nextDue": "2026-09-30"
},
"organizing-week-planner-prep": {
"kind": "task",
"last": "2026-09-20",
"done": 3,
"expected": 4,
"days": [
"2026-09-06",
"2026-09-14",
"2026-09-20"
],
"nextDue": "2026-10-04"
},
"organizing-next-step-awareness-review": {
"kind": "task",
"last": "2026-09-20",
"done": 3,
"expected": 4,
"days": [
"2026-09-06",
"2026-09-14",
"2026-09-20"
],
"nextDue": "2026-10-04"
},
"body-getting-haircut": {
"kind": "task",
"last": "2026-09-19",
"done": 1,
"expected": 1,
"days": [
"2026-09-19"
]
},
"cleaning-wash-tote-bag": {
"kind": "task",
"last": "2026-09-18",
"done": 2,
"expected": 2,
"days": [
"2026-09-04",
"2026-09-18"
],
"nextDue": "2026-10-02"
},
"organizing-reset-medicine-holder": {
"kind": "task",
"last": "2026-09-18",
"done": 3,
"expected": 4,
"days": [
"2026-09-04",
"2026-09-11",
"2026-09-18"
],
"overdueSince": "2026-09-25"
},
"organizing-weekly-grocery-shop": {
"kind": "task",
"last": "2026-09-18",
"done": 3,
"expected": 4,
"days": [
"2026-09-06",
"2026-09-11",
"2026-09-18"
],
"overdueSince": "2026-09-25"
},
"organizing-organize-drawers": {
"kind": "task",
"last": "2026-09-18",
"done": 3,
"expected": 4,
"days": [
"2026-09-04",
"2026-09-11",
"2026-09-18"
],
"overdueSince": "2026-09-25"
},
"organizing-meal-prepping": {
"kind": "task",
"last": "2026-09-18",
"done": 3,
"expected": 4,
"days": [
"2026-09-04",
"2026-09-11",
"2026-09-18"
],
"nextDue": "2026-10-02"
},
"soul-support-session": {
"kind": "task",
"last": "2026-09-17",
"done": 3,
"expected": 4,
"days": [
"2026-09-03",
"2026-09-10",
"2026-09-17"
],
"nextDue": "2026-10-01"
},
"soul-maintenance-session": {
"kind": "task",
"last": "2026-09-16",
"done": 3,
"expected": 4,
"days": [
"2026-09-02",
"2026-09-09",
"2026-09-16"
],
"nextDue": "2026-09-30"
},
"mind-personal-check-in": {
"kind": "task",
"last": "2026-09-14",
"done": 1,
"expected": 2,
"days": [
"2026-09-14"
]
},
"body-feet-care": {
"kind": "task",
"last": "2026-09-14",
"done": 2,
"expected": 4,
"days": [
"2026-09-06",
"2026-09-14"
],
"nextDue": "2026-10-02"
},
"dog-clip-nails": {
"kind": "task",
"last": "2026-09-13",
"done": 1,
"expected": 1,
"days": [
"2026-09-13"
]
},
"cleaning-wash-bedding": {
"kind": "task",
"last": "2026-09-11",
"done": 1,
"expected": 2,
"days": [
"2026-09-11"
]
},
"soul-pinterest-reset": {
"kind": "task",
"last": "2026-09-05",
"done": 1,
"expected": 1,
"days": [
"2026-09-05"
]
},
"organizing-goal-effort-review": {
"kind": "task",
"last": "2026-09-05",
"done": 1,
"expected": 1,
"days": [
"2026-09-05"
],
"nextDue": "2026-10-03"
},
"mind-clothes-audit": {
"kind": "task",
"last": "2026-09-05",
"done": 1,
"expected": 1,
"days": [
"2026-09-05"
],
"nextDue": "2026-10-03"
},
"soul-monthly-review": {
"kind": "task",
"last": "2026-08-31",
"done": 0,
"expected": 1,
"days": [],
"overdueSince": "2026-09-28"
},
"dog-behavior-train-audit": {
"kind": "task",
"last": "2026-08-30",
"done": 0,
"expected": 1,
"days": [],
"nextDue": "2026-09-30"
},
"organizing-life-path-note": {
"kind": "task",
"last": null,
"done": 0,
"expected": 4,
"days": [],
"nextDue": "2026-10-04"
}
}
};
