// GENERATED by tools/build_data.py — snapshot of the live Routines + Goals Sheets,
// used when the Sheets can't be reached. The site re-reads both Sheets live on load.
// The FLOW links are the starting map; edits made on the site override them.

const SNAPSHOT_ROUTINES = [
{
"id": "mind-healthy-minds-session",
"category": "mind",
"focus": "Healthy Minds Sessions",
"why": "To aid in mental growth and being present",
"what": "Awareness Monday, Connection Tuesday, Insight Wednesday, Purpose Thursday, Foundations Friday",
"frequency": "Habit · Mon–Fri",
"freq": 5,
"duration": "One guided session each weekday",
"object": "Healthy Minds App",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "mind-journaling",
"category": "mind",
"focus": "Journal or Self Discovery",
"why": "To channel joys and desires and stay connected to yourself",
"what": "Journal, reflect, or complete a self-discovery practice",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "A page, paragraph, or short prompt",
"object": "Notes, Google Doc, paper, or Bear",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "mind-reading",
"category": "mind",
"focus": "Read (Even 3 Pages)",
"why": "To grow attention span while learning and relaxing the mind",
"what": "Read at least three pages",
"frequency": "Habit · Every 3 days",
"freq": 2.33,
"duration": "Three or more pages",
"object": "Books",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "mind-clothes-audit",
"category": "organizing",
"focus": "Monthly Closet Audit",
"why": "To keep clothing visible, usable, and aligned with your life",
"what": "Review seasonal clothes, shoes, and items to donate or reorganize",
"frequency": "Task · 1st Sat monthly",
"freq": 0.25,
"duration": "Monthly",
"object": "Closet and donation bags",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "mind-smile-to-yourself",
"category": "mind",
"focus": "Smile to Yourself",
"why": "To intentionally create a small moment of warmth and self-connection",
"what": "Pause and smile to yourself",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "A few seconds",
"object": "",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "mind-weekday-reminders",
"category": "mind",
"focus": "Open Grounding (Reminders)",
"why": "To reconnect priorities, purpose, rest, joy, curiosity, and self-assurance with the day",
"what": "Read the grounding reminders and choose the attention the day needs",
"frequency": "Task · Mon–Fri",
"freq": 5,
"duration": "Brief weekday orientation",
"object": "TickTick Grounding list",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "mind-personal-check-in",
"category": "mind",
"focus": "Personal Check In (Bi Weekly)",
"why": "To review routines, projects, tasks, and self-grounding",
"what": "Complete the routines, projects/tasks, and grounding checklist",
"frequency": "Task · Every other Sat",
"freq": 0.5,
"duration": "Bi-weekly",
"object": "TickTick checklist",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "body-cardio-training",
"category": "body",
"focus": "Cardio — Gym",
"why": "To build endurance for summer and festival season",
"what": "Complete the planned cardio session at the gym",
"frequency": "Habit · Tue & Fri",
"freq": 2,
"duration": "Two sessions a week",
"object": "Gym and time",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-protein-intake",
"category": "body",
"focus": "Protein Intake",
"why": "To give the body the proper resources to grow strength",
"what": "Meal prepping, protein shakes, clean eating",
"frequency": "Not in TickTick",
"freq": 0,
"duration": "189g a day",
"object": "Food shopping and protein powder",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "body-vitamins-supplements",
"category": "body",
"focus": "Medicine and Vitamins",
"why": "To support health, recovery, and well-being",
"what": "Take medicine, vitamins, and planned sleep supplements",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "Daily",
"object": "Medicine and supplements",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-abdominal-training",
"category": "body",
"focus": "Abdominal Training — Gym",
"why": "To grow abdominal and internal muscles and sculpt physique",
"what": "Complete the planned abdominal training at the gym",
"frequency": "Habit · Mon & Wed",
"freq": 2,
"duration": "Two sessions a week",
"object": "Gym and time",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-water-intake",
"category": "body",
"focus": "Drink 5 Bottles of Water",
"why": "To support hydration, endurance, recovery, and regulation",
"what": "Drink at least five bottles of water",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "Five bottles",
"object": "Water bottle",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-moisturize-body",
"category": "body",
"focus": "Moisturize Body",
"why": "To support skin health and elasticity",
"what": "Moisturize entire body after shower",
"frequency": "Habit · Sun, Mon, Wed & Fri",
"freq": 4,
"duration": "Four times a week",
"object": "Lotion",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-feet-care",
"category": "body",
"focus": "Foot Care and Moisturize",
"why": "To support flexibility and decrease dead skin cells",
"what": "Footbath, pumice stone, and urea cream",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "Urea cream",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-weekly-bath",
"category": "body",
"focus": "Shower or Epsom Salt Bath",
"why": "To support hygiene, relaxation, and physical recovery",
"what": "Shower daily; on Friday an Epsom salt bath may replace the shower",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "One shower or bath",
"object": "Shower supplies or Epsom salt",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-washing-face-complexion",
"category": "body",
"focus": "Face Washing & Care",
"why": "To help even complexion and support the moisture barrier",
"what": "Wash face and moisturize",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "Daily",
"object": "Face wash and moisturizer",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-getting-haircut",
"category": "body",
"focus": "Schedule Haircut",
"why": "To support hair growth, evenness, and regular grooming",
"what": "Schedule a haircut",
"frequency": "Task · Every 3rd Sat",
"freq": 0.33,
"duration": "Every three weeks",
"object": "Money and preferred barber",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "body-put-out-gym-clothes",
"category": "body",
"focus": "Put Out Gym Clothes",
"why": "To reduce friction before the gym",
"what": "Lay out the next gym outfit",
"frequency": "Habit · Sun–Fri",
"freq": 6,
"duration": "Night before",
"object": "Gym clothes",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "body-nail-cuticle-care",
"category": "body",
"focus": "Nail and Cuticle Care",
"why": "To maintain comfortable, well-kept hands and nails",
"what": "Trim, clean, and care for nails and cuticles",
"frequency": "Task · Wednesday",
"freq": 1,
"duration": "Weekly",
"object": "Nail-care tools",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "soul-main-session",
"category": "soul",
"focus": "Music Session — Main",
"why": "To place the most emphasis on the current music topic",
"what": "Complete the main music session and log the result",
"frequency": "Task · Tuesday",
"freq": 1,
"duration": "Weekly",
"object": "Music setup and session log",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "soul-support-session",
"category": "soul",
"focus": "Music Session — Support",
"why": "To give attention to a supplementary music skill",
"what": "Complete the support music session and log the result",
"frequency": "Task · Thursday",
"freq": 1,
"duration": "Weekly",
"object": "Music setup and session log",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "soul-maintenance-session",
"category": "soul",
"focus": "Music Session — Maintenance",
"why": "To maintain visibility and momentum on recent work",
"what": "Complete the maintenance music session and log the result",
"frequency": "Task · Wednesday",
"freq": 1,
"duration": "Weekly",
"object": "Music setup and session log",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "soul-monthly-review",
"category": "soul",
"focus": "Music Month Review",
"why": "To review progress and choose the next musical emphasis",
"what": "Review the month’s sessions, work, and development",
"frequency": "Task · Last Mon monthly",
"freq": 0.25,
"duration": "Monthly",
"object": "Music session log",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "soul-vocal-training",
"category": "soul",
"focus": "Vocal Training / Warm-Ups",
"why": "To build vocal control, consistency, and recording readiness",
"what": "Complete vocal warm-ups or a focused training session",
"frequency": "Habit · Mon, Wed & Fri",
"freq": 3,
"duration": "Three times a week",
"object": "Vocal exercises",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "soul-pinterest-reset",
"category": "soul",
"focus": "Pinterest Board Reset",
"why": "To keep visual inspiration current and intentional",
"what": "Review and reset Pinterest boards",
"frequency": "Task · 1st Sat every 2 months",
"freq": 0.125,
"duration": "Every two months",
"object": "Pinterest",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "cleaning-wash-bedding",
"category": "cleaning",
"focus": "Wash Bedding",
"why": "To help with complexion and overall dust",
"what": "Strip the duvet and all bedding, wash, dry, and remake the bed",
"frequency": "Task · Every other Fri",
"freq": 0.5,
"duration": "Bi-weekly",
"object": "Detergent",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-vacuum-room",
"category": "cleaning",
"focus": "Vacuum Room",
"why": "To help manage Marvel’s hair and dust",
"what": "Vacuum the room",
"frequency": "Habit · Sun, Tue, Thu & Sat",
"freq": 4,
"duration": "Four times a week",
"object": "Vacuum",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-wipe-room-surfaces",
"category": "cleaning",
"focus": "Wipe Room Surfaces",
"why": "To keep surfaces clean and the space peaceful",
"what": "Wipe down room surfaces",
"frequency": "Habit · Sun, Tue, Thu & Sat",
"freq": 4,
"duration": "Four times a week",
"object": "Rags and cleaner",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-vacuum-car",
"category": "cleaning",
"focus": "Vacuum Car",
"why": "To keep the car clean and peaceful",
"what": "Vacuum the car, ideally around the gym trip",
"frequency": "Task · Saturday",
"freq": 1,
"duration": "Weekly",
"object": "Quarters or car vacuum",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-clean-laundry",
"category": "cleaning",
"focus": "Wash Clothes",
"why": "To ensure smooth daily life and peace",
"what": "Wash, dry, fold, and put away clothes",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "Detergent",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-clean-phone-laptop-glasses",
"category": "cleaning",
"focus": "Wipe Down Phone, Laptop, and Glasses",
"why": "To take care of belongings and feel at peace",
"what": "Remove grime, fingerprints, and dust from daily devices and glasses",
"frequency": "Task · Tue, Thu & Sat",
"freq": 3,
"duration": "Three times a week",
"object": "Alcohol and screen-safe wipes",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-clean-tote-bag",
"category": "cleaning",
"focus": "Clean Out Tote",
"why": "To feel prepared and organized",
"what": "Remove unneeded items and audit the tote’s contents",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-clean-headphones",
"category": "cleaning",
"focus": "Clean Headphones",
"why": "To promote ear health and sound quality",
"what": "Remove wax, dirt, and grime with appropriate wipes",
"frequency": "Task · Mon & Fri",
"freq": 2,
"duration": "Twice a week",
"object": "Alcohol wipes",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "cleaning-wash-tote-bag",
"category": "cleaning",
"focus": "Wash Tote Bag",
"why": "To keep the everyday tote fresh and ready to use",
"what": "Wash and fully dry the tote bag",
"frequency": "Task · Every other Fri",
"freq": 0.5,
"duration": "Bi-weekly",
"object": "Laundry supplies",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "organizing-digital-declutter",
"category": "organizing",
"focus": "Digital Declutter",
"why": "To reduce digital noise and clutter",
"what": "Review emails, contacts, browser history, saved payment methods, and old photos",
"frequency": "Task · Sunday",
"freq": 1,
"duration": "Weekly",
"object": "Phone and computer",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-water-plants",
"category": "organizing",
"focus": "Water Plants",
"why": "To keep plants healthy and alive",
"what": "Water plants according to the plant-care reference",
"frequency": "Task · Monday",
"freq": 1,
"duration": "Weekly",
"object": "Watering container",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-organize-drawers",
"category": "organizing",
"focus": "Reset Drawers, Closet, and Fireplace",
"why": "To keep possessions available and shared spaces reset",
"what": "Reset drawers, closet, and fireplace area",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-weekly-grocery-shop",
"category": "organizing",
"focus": "Put Grocery Order In",
"why": "To enable healthy eating and keep needed food available",
"what": "Submit the weekly grocery order",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "Grocery list and payment method",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-meal-prepping",
"category": "organizing",
"focus": "Meal Prep",
"why": "To enable convenience, healthy eating, and fitness goals",
"what": "Prepare ingredients and meals for the coming week",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "Groceries and a clean kitchen",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-personal-finance-allocation",
"category": "organizing",
"focus": "Weekly Finances Review",
"why": "To keep bills, expenses, purchases, savings, and family needs visible",
"what": "Complete the finance review checklist in TickTick",
"frequency": "Task · Wednesday",
"freq": 1,
"duration": "Weekly",
"object": "Finance trackers",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-savings-allocations",
"category": "organizing",
"focus": "Savings Allocations",
"why": "To ensure excess funds are put aside",
"what": "After personal allocation, move leftover funds to savings as part of Weekly Finances Review",
"frequency": "Task bundle · Wednesday",
"freq": 1,
"duration": "Weekly",
"object": "Next Steps document",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-needed-purchases",
"category": "organizing",
"focus": "Needed / Recurring Purchase Review",
"why": "To ensure a missing object does not block a growth routine",
"what": "Review inventory and needed purchases as part of Weekly Finances Review",
"frequency": "Task bundle · Wednesday",
"freq": 1,
"duration": "Weekly",
"object": "Inventory and purchase list",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-goal-effort-review",
"category": "organizing",
"focus": "Goal Review",
"why": "To ensure effort is going toward something wanted",
"what": "Review personal and life goals and adjust direction",
"frequency": "Task · 1st Sat monthly",
"freq": 0.25,
"duration": "Monthly",
"object": "Goals and effort documents",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-week-planner-prep",
"category": "organizing",
"focus": "Fill in Planner for Week",
"why": "To complete needed things without feeling overwhelmed",
"what": "Fill the planner with tasks and projects for the coming week",
"frequency": "Task · Sunday",
"freq": 1,
"duration": "Weekly",
"object": "Planner",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-next-step-awareness-review",
"category": "organizing",
"focus": "Next Step Awareness Review",
"why": "To turn a larger plan into one visible physical move",
"what": "Open the next-step guide, choose one outcome, and place its next physical action in Next Step Actions",
"frequency": "Task · Sunday",
"freq": 1,
"duration": "Weekly review",
"object": "Next-step guide",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-family-altruism-review",
"category": "organizing",
"focus": "Family Altruism Review",
"why": "To see what effort can support independence and ease transitions",
"what": "Review bucket-list action items as an optional part of Weekly Finances Review",
"frequency": "Task bundle · Wed (optional)",
"freq": 1,
"duration": "Weekly",
"object": "Next Steps document",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-family-finance-review",
"category": "organizing",
"focus": "Family Finance Review",
"why": "To create peace of mind about plans and bill status",
"what": "Review the family finances tracker as an optional part of Weekly Finances Review",
"frequency": "Task bundle · Wed (optional)",
"freq": 1,
"duration": "Weekly",
"object": "House / Family Hub",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "organizing-reset-medicine-holder",
"category": "organizing",
"focus": "Reset Medicine and Vitamin Holder",
"why": "To make the daily medicine and vitamin habit easy to complete",
"what": "Refill and reset the medicine and vitamin organizer",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "Medicine and supplements",
"active": true,
"dateAdded": "2026-08-28"
},
{
"id": "dog-daily-brushing",
"category": "dog",
"focus": "Daily Brushing",
"why": "To help with shedding",
"what": "Brush Marvel in the morning",
"frequency": "Not in TickTick",
"freq": 0,
"duration": "Daily",
"object": "Brush",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "dog-play-sessions",
"category": "dog",
"focus": "Train / Play with Marvel",
"why": "To give Marvel an outlet for energy and strengthen your bond",
"what": "Complete a focused training or play session",
"frequency": "Habit · Mon, Wed & Fri",
"freq": 3,
"duration": "Three times a week",
"object": "Toys, clicker, and treats",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-cuddling",
"category": "dog",
"focus": "Cuddling",
"why": "To bond and snuggle",
"what": "Give Marvel your undivided attention",
"frequency": "Not in TickTick",
"freq": 0,
"duration": "20–30 mins",
"object": "",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "dog-behavior-training",
"category": "dog",
"focus": "Daily Marvel Care — Attention + Enrichment",
"why": "To give Marvel varied attention, stimulation, and care during the workweek",
"what": "Choose from sniff, move, think, cuddle, brush, teeth, or supply care",
"frequency": "Habit · Mon–Fri",
"freq": 5,
"duration": "One meaningful care option",
"object": "Marvel care supplies",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-walks",
"category": "dog",
"focus": "Walk Marvel — Priority",
"why": "To prioritize Marvel’s movement, stimulation, bonding, and regulation",
"what": "Take Marvel for a focused walk",
"frequency": "Habit · Mon, Fri & Sat",
"freq": 3,
"duration": "Three times a week",
"object": "Leash, clicker, treats, and treat tote",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-command-training",
"category": "dog",
"focus": "Command Training",
"why": "To help with command listening",
"what": "Use the Marvel Hub for commands",
"frequency": "Covered by Train / Play habit",
"freq": 0,
"duration": "20–30 mins",
"object": "Clicker and treats",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "dog-weekly-vacuum-marvel",
"category": "dog",
"focus": "Vacuum Brush Marvel",
"why": "To reduce shedding and loose hair",
"what": "Use the vacuum brush attachment",
"frequency": "Habit · Sun, Tue & Thu",
"freq": 3,
"duration": "Three times a week",
"object": "Vacuum brush attachment",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-brush-teeth",
"category": "dog",
"focus": "Brush Teeth",
"why": "To support oral health",
"what": "Use a finger brush to clean Marvel’s teeth",
"frequency": "Not in TickTick",
"freq": 0,
"duration": "Weekly",
"object": "Dog toothbrush",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "dog-supply-inventory-count",
"category": "dog",
"focus": "Marvel Supply Count / Resupply",
"why": "To keep food, treats, chews, and toys available",
"what": "Complete the Marvel supply checklist within Weekly Finances Review",
"frequency": "Task bundle · Wednesday",
"freq": 1,
"duration": "Weekly",
"object": "Marvel supplies",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-behavior-train-audit",
"category": "dog",
"focus": "Marvel Review",
"why": "To review Marvel’s needs and choose the next areas of attention",
"what": "Review routines, behavior, grooming, and supplies",
"frequency": "Task · Monthly on the 30th",
"freq": 0.25,
"duration": "Monthly",
"object": "Marvel Guide",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-supply-organization",
"category": "dog",
"focus": "Supply Organization",
"why": "To audit Marvel’s existing inventory and see what is needed",
"what": "Clean and organize Marvel’s drawers and supplies",
"frequency": "Not in TickTick",
"freq": 0,
"duration": "Bi-weekly",
"object": "",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "dog-clip-nails",
"category": "dog",
"focus": "Schedule Marvel Groomer Visit",
"why": "To maintain grooming, nail health, balance, and comfort",
"what": "Schedule Marvel’s monthly trip to the groomer",
"frequency": "Task · Monthly on the 13th",
"freq": 0.25,
"duration": "Monthly",
"object": "Groomer contact and funds",
"active": true,
"dateAdded": "2026-01-01"
},
{
"id": "dog-behavioral-audit",
"category": "dog",
"focus": "Behavioral Audit",
"why": "To place findings into action",
"what": "Dig into behaviors to work on",
"frequency": "Covered by Marvel Review",
"freq": 0,
"duration": "Monthly",
"object": "",
"active": false,
"dateAdded": "2026-01-01"
},
{
"id": "body-teeth-night",
"category": "body",
"focus": "Teeth Brushing — Night Routine",
"why": "To protect oral health through one dependable nighttime cue",
"what": "Brush teeth; this also includes flossing, mouthwash, and tongue scraping",
"frequency": "Habit · Daily · 11 PM",
"freq": 7,
"duration": "Night routine",
"object": "Oral-care supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-full-gym-session",
"category": "body",
"focus": "Full Gym Session — Complete Flow",
"why": "To build strength through complete, well-formed sessions",
"what": "Warm up, complete the planned sets and reps with enough weight and good form, then cool down",
"frequency": "Habit · Mon–Sat",
"freq": 6,
"duration": "One full planned session",
"object": "Gym plan",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-active-pt",
"category": "body",
"focus": "Active PT — Follow PDF",
"why": "To support healing and movement using the prescribed plan",
"what": "Open the PT PDF and complete the prescribed exercises",
"frequency": "Habit · Mon–Sat",
"freq": 6,
"duration": "Current prescribed session",
"object": "PT PDF",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-creatine-fiber",
"category": "body",
"focus": "Creatine and Fiber Supplements",
"why": "To support training and nutrition with one combined cue",
"what": "Take creatine and fiber together",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "One combined supplement check",
"object": "Creatine and fiber",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "mind-open-job-search",
"category": "organizing",
"focus": "Daily Work & Income Flow",
"why": "To keep required work and income-building actions together in one visible weekday task",
"what": "Job: check Automation Pipeline postings and apply; browse and compile personally found postings and roles; check existing roles and applications. Resale: run the agent posting-stats update; list new items when needed; respond to inquiries; lower prices or offer bundles; ship items when needed; run the trending-items-to-acquire agent. Candles: complete the candle action.",
"frequency": "Task · Mon–Fri",
"freq": 5,
"duration": "Ten checklist items; when-needed items may be skipped when they do not apply",
"object": "Job Hub, resale flow, and candle-making materials",
"active": true,
"dateAdded": "2026-09-08"
},
{
"id": "cleaning-room-reset",
"category": "cleaning",
"focus": "Clean Room Reset",
"why": "To keep the room regulating and usable without creating backlog",
"what": "Return visible items, remove trash, and clear the main walking and working surfaces",
"frequency": "Habit · Daily · Night",
"freq": 7,
"duration": "Daily reset",
"object": "Room-cleaning supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "cleaning-kitchen-usable",
"category": "cleaning",
"focus": "Make Kitchen Usable",
"why": "To keep food preparation available without creating backlog",
"what": "Clear one preparation surface, address dishes, and remove anything blocking cooking",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "Daily reset",
"object": "Kitchen-cleaning supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "mind-daytime-rest",
"category": "mind",
"focus": "Daytime Rest / Quiet Reset",
"why": "To protect regulation and recovery while awake",
"what": "Rest physically or mentally; meditate or choose a simple low-thinking action",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "One genuine pause",
"object": "Quiet space",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-fruit-vegetable",
"category": "body",
"focus": "Eat a Fruit or Vegetable",
"why": "To add a simple antioxidant-rich serving to the day",
"what": "Eat one planned fruit or vegetable serving with a meal",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "One serving",
"object": "Fruit or vegetables",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-movement-break",
"category": "body",
"focus": "Movement Break — Walk, Stretch, or Stand",
"why": "To interrupt long sitting and support energy and mobility",
"what": "Walk, stretch, or stand briefly; even one minute counts",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "One or more brief breaks",
"object": "",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "soul-creative-tinkering",
"category": "soul",
"focus": "Creative / Tinkering Session",
"why": "To make room for curiosity, learning, and unpressured creation",
"what": "Choose curiosity, intentional learning, or unrestricted making",
"frequency": "Habit · Daily",
"freq": 7,
"duration": "One bounded session",
"object": "Chosen creative materials",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "organizing-side-hustle-progress",
"category": "organizing",
"focus": "Side Hustle Progress",
"why": "To keep income-building experiments moving through small actions",
"what": "Resale and candle work now live inside Daily Work & Income Flow",
"frequency": "Covered by Daily Work & Income Flow",
"freq": 0,
"duration": "Preserved reference",
"object": "Selling or candle project materials",
"active": false,
"dateAdded": "2026-08-29"
},
{
"id": "body-face-shaving",
"category": "body",
"focus": "Face Shaving — Every 3 Days",
"why": "To maintain preferred grooming without daily pressure",
"what": "Shave or trim the face to the preferred standard",
"frequency": "Habit · Every 3 days",
"freq": 2.33,
"duration": "One grooming session",
"object": "Shaving supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-body-shaving",
"category": "body",
"focus": "Body Shaving — Weekly",
"why": "To maintain preferred body grooming on a predictable day",
"what": "Complete the selected areas for the self-care session",
"frequency": "Habit · Friday",
"freq": 1,
"duration": "Weekly self-care",
"object": "Shaving supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-recovery-options",
"category": "body",
"focus": "Recovery: TENS/Massage Gun/Dry Brush/Chair/Stretch-Yoga/Relax",
"why": "To respond to the body’s actual recovery needs without six separate habits",
"what": "Choose the recovery support your body needs tonight; one option is enough",
"frequency": "Habit · Daily · 11 PM",
"freq": 7,
"duration": "One chosen recovery option",
"object": "Recovery tools",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "cleaning-bathroom-weekly",
"category": "cleaning",
"focus": "Clean Bathroom — Weekly",
"why": "To keep the bathroom sanitary, regulating, and usable",
"what": "Clean the toilet, sink, mirror, tub or shower, floor, and remove trash",
"frequency": "Task · Saturday",
"freq": 1,
"duration": "Weekly bathroom reset",
"object": "Bathroom-cleaning supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "cleaning-wash-towels",
"category": "cleaning",
"focus": "Wash Towels",
"why": "To keep clean towels available",
"what": "Wash, dry, fold, and put away used towels",
"frequency": "Task · Friday",
"freq": 1,
"duration": "Weekly",
"object": "Laundry supplies",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "organizing-instagram-review",
"category": "organizing",
"focus": "Instagram Following Review",
"why": "To keep the social feed intentional and reduce digital noise",
"what": "Review followed accounts and remove what no longer serves the feed",
"frequency": "Task · Yearly on Apr 1",
"freq": 0.02,
"duration": "Yearly",
"object": "Instagram",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-nutrition-flow-note",
"category": "body",
"focus": "Nutrition Flow — Use Macro Tracker",
"why": "To keep protein, meal spacing, energy snacks, fluids, and supplements visible without duplicating the macro tracker",
"what": "Use the macro tracker; TickTick supplies the supporting action cues",
"frequency": "Reminder · Daily",
"freq": 7,
"duration": "Daily guidance",
"object": "Macro tracker",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "body-gym-standards-note",
"category": "body",
"focus": "Gym Session Standards",
"why": "To define what counts as a full, safe, intentional gym session",
"what": "Warm up, use enough controlled weight, follow tempo and rest, complete planned sets and reps, follow PT, and cool down",
"frequency": "Reminder · Mon–Sat",
"freq": 6,
"duration": "Read with gym plan",
"object": "Gym and PT plans",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "organizing-life-path-note",
"category": "organizing",
"focus": "Life Path & Active Project Direction",
"why": "To keep short-term direction, growth strategy, spiritual alignment, and long-term stability visible",
"what": "Keep outcomes here or in Routine Hub and schedule only the next physical action",
"frequency": "Project reminder · Sunday",
"freq": 1,
"duration": "Weekly direction review",
"object": "Life-path notes",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "organizing-job-search-map-note",
"category": "organizing",
"focus": "Job Search Flow — Coverage Map",
"why": "To make every job-search lane explicit while the detailed process stays external",
"what": "Role applications, automation-found roles, personally found roles, recruiter search, and occupational development",
"frequency": "Reference reminder · Monday",
"freq": 1,
"duration": "Weekly coverage review",
"object": "External job-search flow",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "dog-marvel-care-note",
"category": "dog",
"focus": "Marvel Care & Attention Menu",
"why": "To keep patience, attention, enrichment, grooming, and supplies visible together",
"what": "Use the menu to choose the care Marvel needs today",
"frequency": "Reminder · Mon–Fri",
"freq": 5,
"duration": "Weekday guidance",
"object": "Marvel care menu",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "soul-music-log-note",
"category": "soul",
"focus": "Music Sessions Log",
"why": "To keep links and records for the scheduled music sessions together",
"what": "Open the appropriate session and record what happened",
"frequency": "Reference · Tue, Wed & Thu",
"freq": 3,
"duration": "Three session days a week",
"object": "Music session records",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "soul-creative-project-menu-note",
"category": "soul",
"focus": "Creative / Tinkering & Project Menu",
"why": "To keep deep dives, botanicals, lotions, sewing, knitting, and the baby blanket visible without crowding Today",
"what": "Choose a project and schedule only its next physical action",
"frequency": "Project reminder · Daily",
"freq": 7,
"duration": "Daily project guidance",
"object": "Creative project materials",
"active": true,
"dateAdded": "2026-08-29"
},
{
"id": "mind-rest-sleep-note",
"category": "mind",
"focus": "Rest & Sleep Priorities",
"why": "To protect rest, healing, regulation, energy, and follow-through",
"what": "Use daytime rest when needed and let the nighttime routine support sleep as an outcome",
"frequency": "Reminder · Daily",
"freq": 7,
"duration": "Daily guidance",
"object": "Grounding list",
"active": true,
"dateAdded": "2026-08-29"
}
];

const SNAPSHOT_EFFORTS = [
{
"id": "physical-protein",
"category": "physical",
"effort": "Protein Intake",
"reason": "To help grow muscles for both strength, aesthetic, and endurance",
"how": "170 grams of protein daily via natural sources and protein shakes"
},
{
"id": "physical-hydration",
"category": "physical",
"effort": "Hydrating Our Body",
"reason": "To give our body the required hydration for optimal physical and mental experience",
"how": "3–4 bottles a day (add lime for flavor if not wanting it plain)"
},
{
"id": "physical-selfcare",
"category": "physical",
"effort": "Self Care Practices",
"reason": "To take care of our beautiful body and also grow our confidence and ensure emboldness",
"how": "Follow the self care guide on a routine basis and keep up with needs"
},
{
"id": "physical-nourish",
"category": "physical",
"effort": "Nourishing Our Body",
"reason": "To give our body the proper tools to repair and manage functions for all parts of us",
"how": "Eating whole foods — fruits, vegetables, etc."
},
{
"id": "physical-sleep",
"category": "physical",
"effort": "Getting Good Sleep",
"reason": "To allow peak body repair and feeling rested to take on the world",
"how": "8 hours (7 hour minimum)"
},
{
"id": "physical-vitamins",
"category": "physical",
"effort": "Taking Vitamins / Supps",
"reason": "To supplement or enhance the vitamins we are deriving from foods",
"how": "Using the pill organizer and the purchase sheet to keep up on needs"
},
{
"id": "mental-reading",
"category": "mental",
"effort": "Reading More",
"reason": "To promote a healthy and aware brain while also learning / intaking low stimuli",
"how": "Using the books we have and setting an intention to be curious"
},
{
"id": "mental-journaling",
"category": "mental",
"effort": "Journaling",
"reason": "Present moment awareness — slowing down enough to realize we are all we need to be",
"how": "Using Google Docs as a reflection space, not as a task planner or psychoanalyzer"
},
{
"id": "mental-healthyminds",
"category": "mental",
"effort": "Healthy Minds Sessions",
"reason": "To cover a range of healthy mind practices that in turn grow a richer reality and experience",
"how": "Daily sessions on the Healthy Minds app"
},
{
"id": "mental-cleanspaces",
"category": "mental",
"effort": "Clean Spaces / Things",
"reason": "Less clutter will always equal calm — routine prevents needing to catch up",
"how": "Follow the TickTick schedule and do extra when we can"
},
{
"id": "connection-social",
"category": "connection",
"effort": "Social Connection",
"reason": "To feel connected and cultured — being present with the people in the world around us",
"how": "Look for / plan lunches, fun experiences, momentum"
},
{
"id": "connection-relationships",
"category": "connection",
"effort": "Cultivating Relationships",
"reason": "To give friendship and compassion to someone I can build memories and experiences with",
"how": "To be a villager — put in the effort"
},
{
"id": "connection-experiences",
"category": "connection",
"effort": "Experiences and Pics",
"reason": "Creating novel experiences I can look back on reflectively with proudness",
"how": "Make opportunities for pics"
},
{
"id": "connection-training",
"category": "connection",
"effort": "Training (Marvel)",
"reason": "To help Marvel and I's bond and promote an environment where he knows how to be",
"how": "Following the plan and auditing monthly"
},
{
"id": "financial-credit",
"category": "financial",
"effort": "Credit",
"reason": "To ascertain a credit score that opens the door for us to be independent and long lasting",
"how": "Making active accounts attractive, paying old debts, and a plan for the two big ones"
},
{
"id": "financial-savings",
"category": "financial",
"effort": "Moving Forward Savings",
"reason": "To give us the tools needed to spread our wings into the world, to experience life",
"how": "Using the savings tracker to best build how we are preparing ourselves"
},
{
"id": "financial-material",
"category": "financial",
"effort": "Material",
"reason": "To catch up on odds and ends that cause us disdain",
"how": "Use the sheet to snowball them into a complete state"
},
{
"id": "spiritual-guitar",
"category": "spiritual",
"effort": "Guitar",
"reason": "To embody the art of acoustic songwriting and storytelling",
"how": "Use TickTick reminder with the guitar reference sheet"
},
{
"id": "spiritual-vocal",
"category": "spiritual",
"effort": "Vocal",
"reason": "To give our gift a place to grow and tell the story of emotion through expression",
"how": "Use TickTick reminder with the guitar reference sheet"
},
{
"id": "spiritual-production",
"category": "spiritual",
"effort": "Production",
"reason": "To master how to deliver our creativity to a broad range in a quality and well-done way",
"how": "Use TickTick reminder with the guitar reference sheet"
}
];

const SNAPSHOT_DREAMS = [
{
"id": "travel",
"icon": "🌍",
"dream": "Travel",
"details": "Backpack Europe, hostels, memories",
"how": "Fix credit and have a set place to live and money saved"
},
{
"id": "business",
"icon": "💼",
"dream": "Business",
"details": "A small business, not from a place of desperation",
"how": "Gain security through other avenues first — find time to brainstorm ideas"
},
{
"id": "security",
"icon": "🏡",
"dream": "Security",
"details": "Buy a house after experience",
"how": "Where, credit, when — decide what feels right"
},
{
"id": "tangible",
"icon": "🎁",
"dream": "Something Tangible",
"details": "Real rewards for my efforts — using my potential to its fullest to make life easier",
"how": "Hard work for lasting things — yolo asf"
},
{
"id": "creative",
"icon": "🎸",
"dream": "Creative",
"details": "A music career, a fearless life",
"how": "In motion, but still defining our sound and what we need to know to get there"
}
];

const SEED_ROUTINE_LINKS = {
"mind-healthy-minds-session": {
"tier": "drive",
"efforts": [
"mental-healthyminds"
]
},
"mind-journaling": {
"tier": "drive",
"efforts": [
"mental-journaling"
]
},
"mind-reading": {
"tier": "drive",
"efforts": [
"mental-reading"
]
},
"mind-daytime-rest": {
"tier": "drive",
"efforts": [
"physical-sleep"
]
},
"mind-rest-sleep-note": {
"tier": "drive",
"efforts": [
"physical-sleep"
]
},
"mind-personal-check-in": {
"tier": "upkeep",
"efforts": []
},
"mind-clothes-audit": {
"tier": "upkeep",
"efforts": []
},
"mind-open-job-search": {
"tier": "drive",
"efforts": [
"financial-savings"
]
},
"body-cardio-training": {
"tier": "drive",
"efforts": []
},
"body-abdominal-training": {
"tier": "drive",
"efforts": []
},
"body-full-gym-session": {
"tier": "drive",
"efforts": []
},
"body-active-pt": {
"tier": "drive",
"efforts": []
},
"body-movement-break": {
"tier": "drive",
"efforts": []
},
"body-gym-standards-note": {
"tier": "drive",
"efforts": []
},
"body-protein-intake": {
"tier": "drive",
"efforts": [
"physical-protein"
]
},
"body-nutrition-flow-note": {
"tier": "drive",
"efforts": [
"physical-protein",
"physical-nourish",
"physical-hydration"
]
},
"body-fruit-vegetable": {
"tier": "drive",
"efforts": [
"physical-nourish"
]
},
"body-water-intake": {
"tier": "drive",
"efforts": [
"physical-hydration"
]
},
"body-vitamins-supplements": {
"tier": "drive",
"efforts": [
"physical-vitamins"
]
},
"body-creatine-fiber": {
"tier": "drive",
"efforts": [
"physical-vitamins"
]
},
"body-moisturize-body": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-feet-care": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-weekly-bath": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-washing-face-complexion": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-nail-cuticle-care": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-face-shaving": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-body-shaving": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-recovery-options": {
"tier": "drive",
"efforts": [
"physical-selfcare"
]
},
"body-getting-haircut": {
"tier": "enable",
"efforts": [
"physical-selfcare"
]
},
"body-put-out-gym-clothes": {
"tier": "upkeep",
"efforts": []
},
"body-teeth-night": {
"tier": "upkeep",
"efforts": []
},
"soul-main-session": {
"tier": "drive",
"efforts": [
"spiritual-guitar",
"spiritual-vocal",
"spiritual-production"
]
},
"soul-support-session": {
"tier": "drive",
"efforts": [
"spiritual-guitar",
"spiritual-vocal",
"spiritual-production"
]
},
"soul-maintenance-session": {
"tier": "drive",
"efforts": [
"spiritual-guitar",
"spiritual-vocal",
"spiritual-production"
]
},
"soul-monthly-review": {
"tier": "drive",
"efforts": [
"spiritual-guitar",
"spiritual-vocal",
"spiritual-production"
]
},
"soul-music-log-note": {
"tier": "drive",
"efforts": [
"spiritual-guitar",
"spiritual-vocal",
"spiritual-production"
]
},
"soul-vocal-training": {
"tier": "drive",
"efforts": [
"spiritual-vocal"
]
},
"soul-creative-tinkering": {
"tier": "drive",
"efforts": []
},
"soul-creative-project-menu-note": {
"tier": "drive",
"efforts": []
},
"cleaning-vacuum-room": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-wipe-room-surfaces": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-room-reset": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-kitchen-usable": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-bathroom-weekly": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-wash-bedding": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-clean-laundry": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"cleaning-vacuum-car": {
"tier": "upkeep",
"efforts": []
},
"cleaning-clean-phone-laptop-glasses": {
"tier": "upkeep",
"efforts": []
},
"cleaning-clean-tote-bag": {
"tier": "upkeep",
"efforts": []
},
"cleaning-wash-tote-bag": {
"tier": "upkeep",
"efforts": []
},
"cleaning-clean-headphones": {
"tier": "upkeep",
"efforts": []
},
"cleaning-wash-towels": {
"tier": "upkeep",
"efforts": []
},
"organizing-organize-drawers": {
"tier": "enable",
"efforts": [
"mental-cleanspaces"
]
},
"organizing-weekly-grocery-shop": {
"tier": "enable",
"efforts": [
"physical-nourish",
"physical-protein"
]
},
"organizing-meal-prepping": {
"tier": "enable",
"efforts": [
"physical-nourish",
"physical-protein"
]
},
"organizing-reset-medicine-holder": {
"tier": "enable",
"efforts": [
"physical-vitamins"
]
},
"organizing-personal-finance-allocation": {
"tier": "drive",
"efforts": [
"financial-credit",
"financial-savings"
]
},
"organizing-savings-allocations": {
"tier": "drive",
"efforts": [
"financial-savings"
]
},
"organizing-needed-purchases": {
"tier": "drive",
"efforts": [
"financial-material"
]
},
"organizing-next-step-awareness-review": {
"tier": "enable",
"efforts": [
"financial-credit",
"financial-savings"
]
},
"organizing-side-hustle-progress": {
"tier": "drive",
"efforts": [
"financial-savings"
]
},
"organizing-digital-declutter": {
"tier": "upkeep",
"efforts": []
},
"organizing-water-plants": {
"tier": "upkeep",
"efforts": []
},
"organizing-goal-effort-review": {
"tier": "upkeep",
"efforts": []
},
"organizing-week-planner-prep": {
"tier": "upkeep",
"efforts": []
},
"organizing-family-finance-review": {
"tier": "upkeep",
"efforts": []
},
"organizing-instagram-review": {
"tier": "upkeep",
"efforts": []
},
"organizing-life-path-note": {
"tier": "upkeep",
"efforts": []
},
"organizing-job-search-map-note": {
"tier": "upkeep",
"efforts": []
},
"dog-play-sessions": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-behavior-training": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-walks": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-command-training": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-behavior-train-audit": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-behavioral-audit": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-marvel-care-note": {
"tier": "drive",
"efforts": [
"connection-training"
]
},
"dog-daily-brushing": {
"tier": "upkeep",
"efforts": []
},
"dog-cuddling": {
"tier": "upkeep",
"efforts": []
},
"dog-weekly-vacuum-marvel": {
"tier": "upkeep",
"efforts": []
},
"dog-brush-teeth": {
"tier": "upkeep",
"efforts": []
},
"dog-supply-inventory-count": {
"tier": "upkeep",
"efforts": []
},
"dog-supply-organization": {
"tier": "upkeep",
"efforts": []
},
"dog-clip-nails": {
"tier": "upkeep",
"efforts": []
}
};

const SEED_EFFORT_DREAMS = {
"financial-credit": [
"travel",
"security"
],
"financial-savings": [
"travel",
"business",
"security"
],
"financial-material": [
"tangible",
"security"
],
"connection-experiences": [
"travel"
],
"spiritual-guitar": [
"creative"
],
"spiritual-vocal": [
"creative"
],
"spiritual-production": [
"creative",
"business"
]
};
